### PR TITLE
Update Maven's pom.xml for Jenkins builds

### PR DESCRIPTION
**Pull request by ghost**
I'm working on a Jenkins CI server for Citadel. Jenkins can use Maven
for building projects. This update sets up Citadel for proper Jenkins
builds.

### CODE REVIEW

**Comment by ttk2** [comment]
Sweet, I assume we will be hosting on the meinkraft server? Also could you set it up to also build versions of PrisonPearl? I am not sure if you can do two on the same port though.

**Comment by ghost** [comment]
Yes, Jenkins is up and running on meinkraft on port 8080. To access it from outside, use SSH tunneling. ([here's a tutorial for PuTTY, just in case](http://howto.ccs.neu.edu/howto/windows/ssh-port-tunneling-with-putty/))

Right now I have some issues with java compiler enviroment on meinkraft, but I'm working on it.

**Comment by ttk2** [comment]
Could you not run it on another port? I can do ssh tunneling.

**Comment by ttk2** [comment]
We really really need this to be publicly accessible for it to be useful.

**Comment by ghost** [comment]
I'll try to move Jenkins to another port tomorrow, now it's sleepytime for me (I'm at UTC+0200). PrisonPearl can be easily built on the same server.

**Comment by ttk2** [comment]
Great thanks for your work

**Pull request merged**
