### PR TITLE
workaround fix for 1.4.6, it doesnt remove the placed item if its already removed

### PR DESCRIPTION
**Pull request by intangir**
the bug would allow you to fortify stone with stone for no extra cost

this can work around the oddity

### CODE REVIEW

**Comment by intangir** [comment]
not sure why 1.4.6 somehow breaks it.
it works in 1.4.5 but in 1.4.6 it suddenly doesn't work the same

my guess is it tries to delete the same piece that was already removed.. so i think for the special case of fortifying stone, with stone, we will have to delete 2 stones.. im gonna try it.. very odd

**Comment by ttk2** [comment]
Interesting care to link me to a compiled build so that I can test?

**Comment by erocs** [comment]
What an odd bug. The client acts odd with the placed material too. It looks like it decrements, then it increments back up, and finally using/picking up the material receives a server update and decrements back to the real value.

I sent ttk2 a jar with this.

**Comment by intangir** [comment]
it does a similar thing with item durability of the item in their hand too, it prevents it from changing at all during the event processing if the event is canceled i guess

i am going to instead make a fix that uses a tiny 1 tick delay see if it works better, it would be cleaner

**Pull request merged**
