### PR TITLE
FIX for breaking reinforced snitch blocks.

### PR DESCRIPTION
**Pull request by Celdecea**
Previously the Citadel blockBreak event ran after PreciousStones blockBreak event, allowing snitch blocks to be "broken" even if reinforced (the block remains but doesn't work right). Now Citadel runs before PreciousStones. Exultant had the idea and asked if it would work; as far as I can see it does.

This is a workaround for being able to break snitch blocks behind other reinforced blocks. That particular problem requires a much deeper understanding of how Bukkit and Minecraft events work.

### CODE REVIEW

**Comment by Rudd-O** [comment]
## Shit this is good! 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Celdecea reply@reply.github.com wrote:

Previously Citadel ran after PreciousStones allowing snitch blocks to be "broken" even if reinforced (the block remains but doesn't work right). Now Citadel runs before PreciousStones. Exultant had the idea and asked if it would work; as far as I can see it does.

This is a workaround for being able to break snitch blocks behind other reinforced blocks. That particular problem requires a much deeper understanding of how Bukkit and Minecraft events work.

You can merge this Pull Request by running:

git pull https://github.com/Celdecea/Citadel master

Or you can view, comment on it, or merge it online at:

https://github.com/Exultant/Citadel/pull/42

-- Commit Summary --
- POSSIBLE FIX: Need testing! Seems to prevent hitting the block behind
- Fix for broken snitch blocks behind obsidian. By changing the priority

-- File Changes --

M src/com/untamedears/citadel/listener/BlockListener.java (32)

-- Patch Links --

https://github.com/Exultant/Citadel/pull/42.patch
https://github.com/Exultant/Citadel/pull/42.diff

---

Reply to this email directly or view it on GitHub:
https://github.com/Exultant/Citadel/pull/42

**Comment by ttk2** [comment]
It seems like this can not be auto merged, how do I go about doing it manually? Or how do I let you do it manually?

**Comment by Rudd-O** [comment]
## The author need to rbebase against the latest master, tell you he has done so, and then it will be auto merge able 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Justin reply@reply.github.com wrote:

It seems like this can not be auto merged, how do I go about doing it manually? Or how do I let you do it manually?

---

**Comment by Celdecea** [comment]
I have to learn how to rebase. I'm reading up now.

**Comment by JonnyD** [comment]
Just wondering, are we sure it's a good idea to change the block break method to lowest priority? Couldn't that end up creating the appearance of lag for the client? Also, I have noticed that Minecraft, during heavy load, can ignore events that have lowest priority which means the block break method wont even trigger meaning the code wont be executed and the block break wont be cancelled if it's a reinforcement.

**Comment by JonnyD** [comment]
If you have Eclipse get the plugin EGit. Makes things easier.

**Comment by Celdecea** [comment]
I am using EGit and Git Bash and every single tutorial I can find on the internet. Nothing is getting easier, and I'm fully aware it's completely my fault.

Some nice guy spent two hours on freenod#github actually walking through it with me one screen at a time even he gave up. I want to delete this and start over. It would be easier to apply my few lines of code updates manually than it would be to keep trying to figure out how I am breaking this.

Does anybody know if I can simple delete this whole fork and start fresh?

**Comment by JonnyD** [comment]
I am still new to Git myself but I think what I did was delete my workspace and delete the repository in your .git folder then create a new project, right click and go to Team and 'share project'.

Does anyone know how do I merge the recent changes into my fork? I nearly refactored the whole plugin, nearly finished groups, and don't want to have to start from the beginning.

**Comment by Celdecea** [comment]
Me waiting so long to commit and pull is what seems to hurt me. Apparently make sure you pull and commit from Exultant's before committing your own work. Commit it all and cross your fingers, save your source! ;-)

~~Also I meant properly deleting and starting over on github. I've messaged Github support to make sure I'm not going to break anything. I'm seriously considering just going back to emailing a diff patch to the repository owner for fixes.~~ Everything worked out ok!

I'm still open to suggestions. I'm going to try a couple things after eating some lunch and see what I can do.

**Comment by Celdecea** [comment]
YAY! I think I did it, but I am scared to hit the merge button!

**Comment by ttk2** [comment]
Have you done some testing to see how this affects performance? I will give you the creds to the test server for you to give it a run.

**Comment by Celdecea** [comment]
My credentials for the test server are old. I'd love to do some better stress testing but I don't know how to effectively simulate load for this. If you update me I'll get my jar up there so we can look at it.

**Comment by Celdecea** [comment]
This message seemed hidden:

On 7/15/2012 4:49 PM, Jonathan Devine wrote:

> This seems like a better way to go: http://dev.bukkit.org/server-mods/core/pages/giving-plugins-priority/

If I am not mistaken Bukkit event lowest fires first. If it cancels then 
higher priorities won't fire. Changing the priority with these commits makes Citadel's 
blockBreak run before PreciousStones' which removes the snitch block 
record. I actually don't see how this change could create a performance 
problem at all and seems like a completely natural way to fix the problem.

A whole new mod to do what changing one line of code seems like it would 
be more of a performance hit if there is any to compare to.

**Comment by JonnyD** [comment]
Yeah never mind that link. I just realized how bad that idea was after I read it the whole way through.

Another idea is to edit PreciousStones and just simply add a few lines of code in their block break listener which calls Citadel to check if the block breaking is a reinforcement before destroying the snitch log.

**Comment by Celdecea** [comment]
That would probably double the queries because, as you know, reinforcements are stored in the db. You could run Citadel before and cache the results but what's the point if Citadel can just cancel the event?

**Comment by JonnyD** [comment]
Well, correct me if im wrong, I think since the plugin is using JPA the connection to the database is cached and it's not that much of a performance hit compared to pure MySQL and it will only be called when the jukebox is a snitch. But yeah compared to changing priorities point taken.

**Comment by Rudd-O** [comment]
## The connection being cached is not the same as the queries being cached. The former gives amost not performance, xthe wins are from the latter. 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Jonathan Devine reply@reply.github.com wrote:

Well I think since the plugin is using JPA the connection to the database is cached and it's not that much of a performance hit compared to pure MySQL and it will only be called when the jukebox is a snitch. But yeah compared to changing priorities point taken.

---

**Comment by Rudd-O** [comment]
Fairly simple to rebase

cd into the directory of your repo.  your repo is cloned from your
github fork so you will need to add a remote for the original one.

git remote add upstream
https://....github_url_for_Cloning_i_forget_look_that_up

then git fetch upstream

then you can do git rebase upstream/master

voila, you have rebased.  now you can do git push -f to update your
github fork.

**Comment by JonnyD** [comment]
Cheers for your help! I got it just by merging from upstream but I had to make some edits afterwards which wasn't too difficult.

**Pull request closed without merging**
