### PR TITLE
Make beacon/anvil securable, layer player/natural reinforcements

### PR DESCRIPTION
**Pull request by erocs**

### CODE REVIEW

**Comment by erocs** [comment]
http://www.erocs.org/~erocs/Citadel_i87.jar

**Comment by erocs** [comment]
For 1.4.4+

**Comment by ttk2** [comment]
Will this work on pre 1.4.4? Or should I wait around on that?

**Comment by erocs** [comment]
I put that in there because I couldn't remember what would happen with unknown blocks in the config. Taking a look now and it should work fine. You'll just get "Invalid additionalSecurable material" messages displayed for ANVIL and BEACON.

**Pull request merged**
